name: Trigger VPS Doc Build

on:
  push:
    branches:
      - 'main'        # All branches (or use ['main', 'dev'] if you prefer)
    paths:
      - 'docs/**'  # Only trigger when docs change (optional)

jobs:
  call-vps-webhook:
    runs-on: ubuntu-latest
    env:
      SECRET: ${{ secrets.SPHINXTESTSECRET }}
      REPO_NAME: ${{ github.event.repository.name }}
      REPO_PATH: "https://github.com/R-C137/SphinxTest.git"
	

    steps:
      - name: Get branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Call VPS webhook
        run: |
          JSON=$(jq -n \
            --arg repo "$REPO_NAME" \
            --arg branch "$BRANCH_NAME" \
            --arg path "$REPO_PATH" \
            '{repo: $repo, branch: $branch, repo_path: $path}')

          SIG=$(echo -n "$JSON" | openssl dgst -sha256 -hmac "$SECRET" | sed 's/^.* //')

          curl -X POST https://docs.clogic.dev/build-docs \
            -H "Content-Type: application/json" \
            -H "X-Hub-Signature-256: sha256:$SIG" \
            -d "$JSON"
