name: Trigger VPS Doc Build

on:
  push:
    branches:
      - 'main'
    paths:
      - 'docs/**'

jobs:
  call-vps-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Set BRANCH_NAME
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set REPO_NAME
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Call VPS webhook
        env:
          SECRET: ${{ secrets.SPHINXTESTSECRET }}
        run: |
          echo '{"repo":"SphinxTest","branch":"main","repo_path":"https://github.com/R-C137/SphinxTest.git"}' > payload.json

          SIG=$(openssl dgst -sha256 -hmac "$SECRET" payload.json | sed 's/^.* //')

          echo "--- JSON Payload ---"
          cat payload.json
          echo "--- Signature ---"
          echo "sha256:$SIG"

          curl -X POST https://docs.clogic.dev/build-docs \
          -H "Content-Type: application/json" \
          -H "X-Hub-Signature-256: sha256:$SIG" \
          --data-binary "@payload.json"
